"""Migrations package — files generated by Alembic land here.

`alembic init` would normally drop a `versions/` folder and a `script.py.mako`.
We instead keep everything under `backend/alembic/` so the standard
`alembic upgrade head` workflow Just Works.
"""
